opi/core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from website import urls as wesiturl
from website import views as view
from payment import urls as nhj
from promotion import urls as promotio
from django.views.generic import TemplateView

urlpatterns = [

    url(r'^schedule/', include('schedule.urls')),
    url(r'^fullcalendar/', TemplateView.as_view(template_name="fullcalendar.html"), name='fullcalendar'),

    path('admin/', admin.site.urls),          # Django admin route
    path("", include(("apps.authentication.urls", "account"),namespace='account')), # Auth routes - login / register
    path("", include(("home.urls", "main"),namespace='main')),
    path("", include("allauth.urls")),
    path('webuse/',include("webuser.urls")), #my app urls
    path('website/', include((wesiturl,'website'),namespace='website')),
    path('paypal/', include('paypal.standard.ipn.urls')),      
    path('payment/', include((nhj,'payment'),namespace='payment')),
    url(r'^getdatareport/', view.getdatareport),#api for get usernewuser
    path('newuser/<str:id>', view.newuser),
    path('storedata/<str:id>', view.storedata),#api for requesing from 
   
         # UI Kits Html files

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

opi/home/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from .views import *

urlpatterns = [

    # The home page
    path('', index, name='home'),
    path('test', test, name='test'),

    # Matches any html file
    #re_path(r'^.*\.*', views.pages, name='pages'),

]

opi/promotion/urls.py
from django.urls import path
from . import views
urlpatterns = [
]

opi/website/urls.py
from django.urls import path
from . import views
urlpatterns = [
   path('',views.home),
   path('view',views.vie, name = 'register'),
   path('offerlist/<str:mid>', views.offerlist, name = 'offerlist'),
   path('offerlist_in/<str:mid>/<str:temp>', views.offerlist_in, name = 'offerlist_in'),
   path('webeditpage/<str:mid>', views.webeditpage, name = 'webeditpage'),
   path('cheack', views.cheack, name = 'cheack'),
   path('update/<str:id>', views.update, name = 'update'),
   path('upload/<str:id>', views.upload, name = 'upload'),
   path('upload_first/<str:id>', views.upload_first, name = 'upload_first'),
   path('imupdate/<str:id>', views.imupdate, name = 'imupdate'),
   path('updatetable/<str:id>', views.updatetable, name = 'updatetable'),
   path('removtable/<str:id>', views.removtable, name = 'removtable'),
   path('resat/<str:id>', views.resat, name = 'resat'),
   path('restart/<str:id>', views.restart1, name = 'restart'),
   path('stop/<str:id>', views.stop, name = 'stop'),
   path('reload/<str:id>', views.reload1, name = 'reload'),
   path('registernew', views.registernew, name = 'registernew'),
   path('selectweb_type/<str:name>', views.selectweb_type, name = 'selectweb_type'),
   path('selecttemplate/<str:name>/<str:type1>', views.selecttemplate, name = 'selecttemplate'),
   path('view_template/<str:name>/<str:tmid>', views.view_template, name = 'view_template'),
   path('template_edit/<str:id>', views.template_edit, name = 'template_edit'),

   path('billing/<str:id>', views.billing, name = 'billing'),
   path('select_domain/<str:id>', views.select_domain, name = 'select_domain'),
   path('select_domain_remove/<str:id>', views.select_domain_remove, name = 'select_domain_remove'),
   path('payment/<str:id>', views.payment, name = 'payment'),
   path('dataentrypage/<str:id>', views.dataentrypage, name = 'dataentrypage'),
   path('register_email/<str:id>', views.register_email, name = 'register_email'),
   path('remove_email/<str:id>', views.remove_email, name = 'remove_email'),
   path('setup_promo/<str:id>', views.setup_promo, name = 'setup_promo'),
   path('remove_promo/<str:id>', views.remove_promo, name = 'remove_promo'),
   path('dataentrypage_main/<str:id>', views.dataentrypage_main, name = 'dataentrypage_main'),
   

   path('edit_page/<str:id>', views.edit_pages, name = 'edit_pages'),
   path('upload_first1/<str:id>', views.upload_first1, name = 'upload_first1'),
   path('domain_name/<str:id>', views.domain_name, name = 'domain_name'),
   path('domain_removemain/<str:id>', views.domain_removemain, name = 'domain_removemain'),
   path('domain_selected/<str:id>', views.domain_selec, name = 'domain_selected'),
   path('promotion/<str:id>', views.promotion, name = 'promotion'),
   path('livereport/<str:id>', views.livereport, name = 'livereport'),
   path('messages/<str:id>', views.messages, name = 'messages'),
]

opi/home/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

opi/promotion/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from schedule.models import Event as SchedulerEvent
from webuser.models import webservice as webservice
from django.db.models import CASCADE
from django_countries.fields import CountryField

class daily_data(models.Model):
    webservice = models.ForeignKey(webservice, on_delete=CASCADE, blank=True, null=True)
    count = models.IntegerField(default=1)
    rday = models.DateField(auto_now_add=True)

class country_data(models.Model):
    webservice = models.ForeignKey(webservice, on_delete=CASCADE, blank=True, null=True)
    cantry = models.CharField(null=True, unique=False, max_length=500)
    cun = CountryField(null = True)
    count = models.IntegerField(default=1)
    rday = models.DateField(auto_now_add=True)

class refral_data(models.Model):
    webservice = models.ForeignKey(webservice, on_delete=CASCADE, blank=True, null=True)
    ref = models.CharField(null=True, unique=False, max_length=500)
    count = models.IntegerField(default=1)
    rday = models.DateField(auto_now_add=True)

class vister_data(models.Model):
    webservice = models.ForeignKey(webservice, on_delete=CASCADE, blank=True, null=True)
    ref = models.CharField(null=True, unique=False, max_length=500)
    country = models.CharField(null=True, unique=False, max_length=200)
    cun = CountryField(null = True)
    ip = models.CharField(null=True, unique=False, max_length=200)
    location = models.CharField(null=True, unique=False, max_length=200)
    time = models.CharField(null=True, unique=False, max_length=200)
    rday = models.DateField(auto_now_add=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        try:
            payme = daily_data.objects.get(webservice = self.webservice, rday = self.rday)
            payme.count += 1
            payme.save()
        except daily_data.DoesNotExist:
            payme = daily_data.objects.create(webservice = self.webservice)

        try:
            payme11 = country_data.objects.get(webservice = self.webservice, cantry = self.country)
            payme11.count += 1
            payme11.save()
        except country_data.DoesNotExist:
            payme11 = country_data.objects.create(webservice = self.webservice, cun = self.cun,cantry = self.country)

        if self.ref != '':
            try:
                payme22 = refral_data.objects.get(webservice = self.webservice, ref = self.ref)
                payme22.count += 1
                payme22.save()
            except refral_data.DoesNotExist:
                payme22 = refral_data.objects.create(webservice = self.webservice,ref = self.ref)
        else:
            try:
                payme22 = refral_data.objects.get(webservice = self.webservice, ref = "Direct")
                payme22.count += 1
                payme22.save()
            except refral_data.DoesNotExist:
                payme22 = refral_data.objects.create(webservice = self.webservice,ref = "Direct")             

opi/promotion/forms.py
from django import forms
from schedule.forms import EventForm
from .models import MyEvent

class MyEventForm(EventForm):
    field_x = forms.CharField(max_length=50)

    class Meta:
        model = MyEvent
        fields = '__all__'

opi/home/views.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django import template
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.shortcuts import render, redirect
from website.models import *
from webuser.models import *


def test(request):
    if request.user.is_authenticated:
        context = {'webid': '1', "file":request.user}
        html_template = loader.get_template('home/dashboard.html')
        return HttpResponse(html_template.render(context, request))

@login_required(login_url="/login/")
def index(request):
    if request.user.is_authenticated:
        if webservice.objects.filter(client = request.user).exists():
            context = {'project': webservice.objects.filter(client = request.user)}
            html_template = loader.get_template('home/secondpage.html')
            return HttpResponse(html_template.render(context, request))
        else:
            context = {'segment': 'index'}
            html_template = loader.get_template('home/firstlogin.html')
            return HttpResponse(html_template.render(context, request))
    else:
        context = {'segment': 'index'}
        html_template = loader.get_template('home/index.html')
        return HttpResponse(html_template.render(context, request))



@login_required(login_url="/login/")
def pages(request):
    context = {}
    # All resource paths end in .html.
    # Pick out the html file name from the url. And load that template.
    try:

        load_template = request.path.split('/')[-1]

        if load_template == 'admin':
            return HttpResponseRedirect(reverse('admin:index'))
        context['segment'] = load_template

        html_template = loader.get_template('home/' + load_template)
        return HttpResponse(html_template.render(context, request))

    except template.TemplateDoesNotExist:

        html_template = loader.get_template('home/page-404.html')
        return HttpResponse(html_template.render(context, request))

    except:
        html_template = loader.get_template('home/page-500.html')
        return HttpResponse(html_template.render(context, request))

opi/apps/templates/home/domainview.html
{% extends "layouts/base-fullscreen.html" %}
{% load django_htmx %}
{% block title %} Sign UP {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <main>
        <section class="vh-lg-100 mt-5 mt-lg-0 bg-soft d-flex align-items-center">
            <div class="container">
                <p class="text-center">
                </p>
                <div class="row justify-content-center form-bg-image" data-background-lg="/static/assets/img/illustrations/signin.svg">
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="bg-white shadow border-0 rounded border-light p-4 p-lg-5 w-100 fmxw-500">
                            <div class="text-center text-md-center mb-4 mt-md-0">
                                
                                <h1 class="mb-0 h3">
                                    Domain & email name setup 
                                </h1>
                                <br />
                                {% if avel == 0 %}
                                <p>
                                   Do you need Domain Name for your website?                                         
                                </p> 
                                <label>
                                    <input type="checkbox" id="myCheckbox">
                                    Yes
                                  </label>
                                  {% else %}
                                  <p>
                                    List of domian you have chosed for your website, we will look for available domains names and setup on your website.                                    
                                 </p> 
                                 <ul class="list-group list-group-flush price-list">
                                    {% for n in dlist %}
                                    <li class="list-group-item d-flex align-items-center border-0 ps-0"><svg class="icon icon-xs text-success me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path></svg> 
                                        {{n.name}}
                                        <form action="{% url 'website:select_domain_remove' webid %}" method="post">
                                            {% csrf_token %}
                                            <input type="text" name="id" value="{{n.id}}" hidden >
                                            <button type="submit" class="btn btn">remove</button>
                                        </form>
                                    </li>
                                    {% endfor %}
                                </ul>
                                 {% endif %}
                            </div>
                            {% if avel == 0 %}
                            <div id="optionalField" style="display: none;" class="mt-3 mb-4 text-center">
                                <form action="" method="post">
                                    {% csrf_token %}
                                    <div class=" d-flex align-items-center justify-content-center mb-5">
                                        <div class=" col-10 mb-5">
                                            <label for="firstName">Eneter domain name for your websit</label>
                                            <input type="text" class="form-control " name="name" required >
                                                           
                                        </div>
        
                                    </div>
                                    <!-- Button Modal -->
                                    
                                    <div class="d-grid">
                                        <button type="submit" name="register" class="btn btn-gray-800">Find me Domain name</button>
                                    </div>
                                </form>
                                    
                              </div>
                              <div id="optionalField1" class="mt-3 mb-4 text-center">
                                <label for="optionalInput">{{servis.name}}.Zufan.com</label>
                              </div>
                            
                            <div class="d-flex justify-content-center align-items-center mt-4">
                                <span class="fw-normal">
                                    If you dont need a domain name you can simply prees next
                                </span>
                            </div>
                            {% else %}
                                <div class="mt-3 mb-4 text-center">
                                    {% if 2 >= avel %}
                                    <form action="" method="post">
                                        {% csrf_token %}
                                        <div class=" d-flex align-items-center justify-content-center mb-5">
                                            <div class=" col-8 mb-5">
                                                <label for="firstName">Eneter domain name for your websit</label>
                                                <input type="text" class="form-control " name="name" required ><br>
                                                            
                                            
            
                                        
                                        <div class="d-grid">
                                            <button type="submit" name="register" class="btn btn-gray-800">Find me Domain name</button>
                                        </div>
                                        </div>
                                        </div>
                                    </form>
                                    {% endif %}
                                    <hr>
                                    {% if email_t == 0 %}
                                        <p>
                                            Do you need Email address under your domain?                                         
                                        </p> 
                                     <label>
                                         <input type="checkbox" id="myCheckboxemail">
                                         Yes
                                       </label>
                                       <div id="emailshowe" style="display: none;" class="mt-3 mb-4 text-center">
                                        <form action="{% url 'website:register_email' webid %}" method="post">
                                            {% csrf_token %}
                                            <select class="form-select" name="etype" aria-label="Default select example">
                                                {% for i in emailtype %}
                                                <option value="{{i.id}}">{{i.name}}-{{i.cost}}</option>
                                                {% endfor %}
                                            </select>
                                            <div class="d-grid">
                                                <button type="submit" name="register" class="btn btn-gray-800">Add email</button>
                                            </div>
                                        </form>
                                      </div>
                                      {% else %}
                                      <p>
                                        you have selected                                          
                                    </p> 
                                    <ul class="list-group list-group-flush price-list">
                                        <li class="list-group-item d-flex align-items-center border-0 ps-0"><svg class="icon icon-xs text-success me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path></svg> 
                                            {{email.0.email_type.name}} - {{email.0.cost}}<hr>
                                            {{email.0.email_type.info}}
                                            <form action="{% url 'website:remove_email' webid %}" method="post">
                                                {% csrf_token %}
                                                <input type="text" name="id" value="{{email.0.id}}" hidden >
                                                <button type="submit" class="btn btn">remove</button>
                                            </form>
                                        </li>
                                    </ul>
                                 <label>
                                    <p>if you wish to change select from the list</p>
                                   <div  class="mt-3 mb-4 text-center">
                                    <form action="{% url 'website:register_email' webid %}" method="post">
                                        {% csrf_token %}
                                        <select class="form-select" name="etype" aria-label="Default select example">
                                            {% for i in emailtype %}
                                            <option value="{{i.id}}">{{i.name}}-{{i.cost}}</option>
                                            {% endfor %}
                                        </select>
                                        <div class="d-grid">
                                            <button type="submit" name="register" class="btn btn-gray-800">Add email</button>
                                        </div>
                                    </form>
                                  </div>
                                      {% endif %}
                                        
                                </div>

                            {% endif %}
                            <a 
                                href="{% url 'website:setup_promo' webid%}"
                               class="btn btn-secondary d-flex align-items-center">
                               <span class="sidebar-icon d-inline-flex align-items-center justify-content-center">
                                 <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M12.395 2.553a1 1 0 00-1.45-.385c-.345.23-.614.558-.822.88-.214.33-.403.713-.57 1.116-.334.804-.614 1.768-.84 2.734a31.365 31.365 0 00-.613 3.58 2.64 2.64 0 01-.945-1.067c-.328-.68-.398-1.534-.398-2.654A1 1 0 005.05 6.05 6.981 6.981 0 003 11a7 7 0 1011.95-4.95c-.592-.591-.98-.985-1.348-1.467-.363-.476-.724-1.063-1.207-2.03zM12.12 15.12A3 3 0 017 13s.879.5 2.5.5c0-1 .5-4 1.25-4.5.5 1 .786 1.293 1.371 1.879A2.99 2.99 0 0113 13a2.99 2.99 0 01-.879 2.121z" clip-rule="evenodd"></path></svg>
                               </span> 
                               <span>Next</span>
                             </a>
                                
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
    {% if avel == 0 %}
    <script>
        var checkbox = document.getElementById('myCheckbox');
        var optionalField = document.getElementById('optionalField');
        var optionalField1 = document.getElementById('optionalField1');
        var optionalField2 = document.getElementById('optionalField2');
        
        checkbox.addEventListener('change', function() {
          if (checkbox.checked) {
            optionalField.style.display = 'block';
            optionalField1.style.display = 'none';
            optionalField2.style.display = 'none';
          } else {
            optionalField.style.display = 'none';
            optionalField1.style.display = 'block';
            optionalField2.style.display = 'block';
          }
        });



        </script>
        {% else %}
        <script>
        var checkboxemail = document.getElementById('myCheckboxemail');
        var emailshowe = document.getElementById('emailshowe');
        
        
     

        checkboxemail.addEventListener('change', function() {
          if (checkboxemail.checked) {
            emailshowe.style.display = 'block';
          } else {
            emailshowe.style.display = 'none';
          }
        });


        </script>
        {% endif %}

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

opi/apps/templates/home/page-403.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Error 403 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <main>
        <section class="vh-100 d-flex align-items-center justify-content-center">
            <div class="container">
                <div class="row">
                    <div class="col-12 text-center d-flex align-items-center justify-content-center">
                        <div>
                            <img class="img-fluid w-75" src="/static/assets/img/illustrations/404.svg" alt="404 not found">
                            <h1 class="mt-5">
                                Access <span class="fw-bolder text-primary">denied</span>
                            </h1>
                            <p class="lead my-4">
                                Please contact support or authenticate
                            </p>
                            <a class="btn btn-dark animate-hover" href="/sign-in.html">
                               <i class="fas fa-chevron-left me-3 ps-2 animate-left-3"></i>LOGIN</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

opi/apps/templates/home/page-lock.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Page Lock {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <main>
        <section class="vh-lg-100 mt-5 mt-lg-0 bg-soft d-flex align-items-center">
            <div class="container">
                <a href="/dashboard.html" class="d-flex align-items-center justify-content-center mb-4">
                    <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.707 14.707a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l2.293 2.293a1 1 0 010 1.414z" clip-rule="evenodd"></path></svg>
                    Back to homepage
                </a>
                <div class="row justify-content-center form-bg-image" data-background-lg="/static/assets/img/illustrations/signin.svg">
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="bg-white shadow border-0 rounded p-4 p-lg-5 w-100 fmxw-500">
                            <div class="text-center text-md-center mb-4 mt-md-0">
                                <div class="avatar avatar-lg mx-auto mb-3"><img class="rounded-circle" alt="Image placeholder" src="/static/assets/img/team/profile-picture-3.jpg"></div>
                                <h1 class="h3">Bonnie Green</h1>
                                <p class="text-gray">Better to be safe than sorry.</p>
                            </div>
                            <form class="mt-5">
                                <!-- Form -->
                                <div class="form-group mb-4">
                                    <label for="password">Your Password</label>
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon2">
                                            <svg class="icon icon-xs text-gray-600" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clip-rule="evenodd"></path></svg>
                                        </span>
                                        <input type="password" placeholder="Password" class="form-control" id="password" required>
                                    </div>  
                                </div>
                                <!-- End of Form -->
                                <div class="d-grid mt-3">
                                    <button type="submit" class="btn btn-gray-800">Unlock</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}