opi/apps/authentication/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path
from .views import login_view, register_user
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('login/', login_view, name="login"),
    path('register/', register_user, name="register"),
    path("logout/", LogoutView.as_view(), name="logout")
]

opi/core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from website import urls as wesiturl
from website import views as view
from payment import urls as nhj
from promotion import urls as promotio
from django.views.generic import TemplateView

urlpatterns = [

    url(r'^schedule/', include('schedule.urls')),
    url(r'^fullcalendar/', TemplateView.as_view(template_name="fullcalendar.html"), name='fullcalendar'),

    path('admin/', admin.site.urls),          # Django admin route
    path("", include(("apps.authentication.urls", "account"),namespace='account')), # Auth routes - login / register
    path("", include(("home.urls", "main"),namespace='main')),
    path("", include("allauth.urls")),
    path('webuse/',include("webuser.urls")), #my app urls
    path('website/', include((wesiturl,'website'),namespace='website')),
    path('paypal/', include('paypal.standard.ipn.urls')),      
    path('payment/', include((nhj,'payment'),namespace='payment')),
    url(r'^getdatareport/', view.getdatareport),#api for get usernewuser
    path('newuser/<str:id>', view.newuser),
    path('storedata/<str:id>', view.storedata),#api for requesing from 
   
         # UI Kits Html files

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

opi/website/urls.py
from django.urls import path
from . import views
urlpatterns = [
   path('',views.home),
   path('view',views.vie, name = 'register'),
   path('offerlist/<str:mid>', views.offerlist, name = 'offerlist'),
   path('offerlist_in/<str:mid>/<str:temp>', views.offerlist_in, name = 'offerlist_in'),
   path('webeditpage/<str:mid>', views.webeditpage, name = 'webeditpage'),
   path('cheack', views.cheack, name = 'cheack'),
   path('update/<str:id>', views.update, name = 'update'),
   path('upload/<str:id>', views.upload, name = 'upload'),
   path('upload_first/<str:id>', views.upload_first, name = 'upload_first'),
   path('imupdate/<str:id>', views.imupdate, name = 'imupdate'),
   path('updatetable/<str:id>', views.updatetable, name = 'updatetable'),
   path('removtable/<str:id>', views.removtable, name = 'removtable'),
   path('resat/<str:id>', views.resat, name = 'resat'),
   path('restart/<str:id>', views.restart1, name = 'restart'),
   path('stop/<str:id>', views.stop, name = 'stop'),
   path('reload/<str:id>', views.reload1, name = 'reload'),
   path('registernew', views.registernew, name = 'registernew'),
   path('selectweb_type/<str:name>', views.selectweb_type, name = 'selectweb_type'),
   path('selecttemplate/<str:name>/<str:type1>', views.selecttemplate, name = 'selecttemplate'),
   path('view_template/<str:name>/<str:tmid>', views.view_template, name = 'view_template'),
   path('template_edit/<str:id>', views.template_edit, name = 'template_edit'),

   path('billing/<str:id>', views.billing, name = 'billing'),
   path('select_domain/<str:id>', views.select_domain, name = 'select_domain'),
   path('select_domain_remove/<str:id>', views.select_domain_remove, name = 'select_domain_remove'),
   path('payment/<str:id>', views.payment, name = 'payment'),
   path('dataentrypage/<str:id>', views.dataentrypage, name = 'dataentrypage'),
   path('register_email/<str:id>', views.register_email, name = 'register_email'),
   path('remove_email/<str:id>', views.remove_email, name = 'remove_email'),
   path('setup_promo/<str:id>', views.setup_promo, name = 'setup_promo'),
   path('remove_promo/<str:id>', views.remove_promo, name = 'remove_promo'),
   path('dataentrypage_main/<str:id>', views.dataentrypage_main, name = 'dataentrypage_main'),
   

   path('edit_page/<str:id>', views.edit_pages, name = 'edit_pages'),
   path('upload_first1/<str:id>', views.upload_first1, name = 'upload_first1'),
   path('domain_name/<str:id>', views.domain_name, name = 'domain_name'),
   path('domain_removemain/<str:id>', views.domain_removemain, name = 'domain_removemain'),
   path('domain_selected/<str:id>', views.domain_selec, name = 'domain_selected'),
   path('promotion/<str:id>', views.promotion, name = 'promotion'),
   path('livereport/<str:id>', views.livereport, name = 'livereport'),
   path('messages/<str:id>', views.messages, name = 'messages'),
]

opi/apps/templates/includes/footer.html
<footer class="bg-white rounded shadow p-5 mb-4 mt-4">
    <div class="row">
        <div class="col-12 col-md-4 col-xl-6 mb-4 mb-md-0">
            <p class="mb-0 text-center text-lg-start">
                &copy; <a class="text-primary fw-normal" href="https://themesberg.com" target="_blank">Themesberg</a>
                - Coded by <a href="https://appseed.us" target="_blank">AppSeed</a>.
            </p>
        </div>
        <div class="col-12 col-md-8 col-xl-6 text-center text-lg-start">
            <!-- List -->
            <ul class="list-inline list-group-flush list-group-borderless text-md-end mb-0">
                <li class="list-inline-item px-0 px-sm-2">
                    <a target="_blank" 
                       href="https://appseed.us/admin-dashboards/django-dashboard-volt">Django Volt Dashboard</a>
                </li>
            </ul>
        </div>
    </div>
</footer>

opi/apps/templates/includes/message.html
{% for message in messages %}
<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
    
    {{ message }}
  </div>
</div>
{% endfor %}

opi/apps/templates/includes/navigation.html
<nav class="navbar navbar-top navbar-expand navbar-dashboard navbar-dark ps-0 pe-2 pb-0">
              <div class="container-fluid px-0">
                <div class="d-flex justify-content-between w-100" id="navbarSupportedContent">
                  <div class="d-flex align-items-center">
                    <!-- Search form -->
                    {% if file.active == False %}
                    <form action="" class="navbar-search form-inline" id="navbar-search-main" method="post">
                      {% csrf_token %} 
                      <div class="input-group input-group-merge search-bar">
                          
                          <button class="btn btn-success" type="submit">Deploy</button>
                       </div>
                    </form>
                    {% else %}
                    <form action="{%url 'website:restart' webid %}" method="post" class="navbar-search form-inline" id="navbar-search-main">
                      {% csrf_token %}
                      <div class="input-group input-group-merge search-bar">
                          
                          <button class="btn btn-success" type="submit">Restart</button>
                       </div>
                    </form>
                    <form action="{%url 'website:reload' webid %}" method="post" class="navbar-search form-inline" id="navbar-search-main">
                      {% csrf_token %}
                      <div class="input-group input-group-merge search-bar">
                          
                          <button class="btn btn-warning" type="submit">Reload</button>
                       </div>
                    </form>
                    <form action="{%url 'website:stop' webid %}" method="post" class="navbar-search form-inline" id="navbar-search-main">
                      {% csrf_token %}
                      <div class="input-group input-group-merge search-bar">
                          
                          <button class="btn btn-danger" type="submit">Stop</button>
                       </div>
                    </form>
                    <form class="navbar-search form-inline" action="{%url 'website:resat' webid %}" method="post" id="navbar-search-main">
                      <div class="input-group input-group-merge search-bar">
                      {% csrf_token %} 
                      <button class="btn btn-danger" type="submit">Resat</button>
                    </div>
                    </form>
                    {% endif %}

                    <!-- / Search form -->
                  </div>
                  <div class="d-flex align-items-center">
                    <h4>{{file.name}} : {{file.port}} </h4>
                  </div>
                  <!-- Navbar links -->
                  <ul class="navbar-nav align-items-center">
                    <li class="nav-item dropdown">
                      <a class="nav-link text-dark notification-bell unread dropdown-toggle" data-unread-notifications="true" href="#" role="button" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
                        <svg class="icon icon-sm text-gray-900" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M10 2a6 6 0 00-6 6v3.586l-.707.707A1 1 0 004 14h12a1 1 0 00.707-1.707L16 11.586V8a6 6 0 00-6-6zM10 18a3 3 0 01-3-3h6a3 3 0 01-3 3z"></path></svg>
                      </a>
                      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-center mt-2 py-0">
                        <div class="list-group list-group-flush">
                          <a href="#" class="text-center text-primary fw-bold border-bottom border-light py-3">Notifications</a>
                          {% for i in notif %}
                          <a href="#" class="list-group-item list-group-item-action border-bottom">
                            <div class="row align-items-center">
                                
                                <div class="col ps-0 ms-2">
                                  <div class="d-flex justify-content-between align-items-center">
                                      <div>
                                        <h4 class="h6 mb-0 text-small">{{i.name}}</h4>
                                      </div>
                                      <div class="text-end">
                                        <small class="text-danger">{{i.rday}}</small>
                                      </div>
                                  </div>
                                  <p class="font-small mt-1 mb-0">{{i.info}}</p>
                                </div>
                            </div>
                          </a>
                          {% endfor %}
                          
                          <a href="#" class="dropdown-item text-center fw-bold rounded-bottom py-3">
                            <svg class="icon icon-xxs text-gray-400 me-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M10 12a2 2 0 100-4 2 2 0 000 4z"></path><path fill-rule="evenodd" d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z" clip-rule="evenodd"></path></svg>
                            View all
                          </a>
                        </div>
                      </div>
                    </li>
                    <li class="nav-item dropdown ms-lg-3">
                      <a class="nav-link dropdown-toggle pt-1 px-0" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <div class="media d-flex align-items-center">
                          <img class="avatar rounded-circle" alt="Image placeholder" src="/static/assets/img/team/profile-picture-3.jpg">
                          <div class="media-body ms-2 text-dark align-items-center d-none d-lg-block">
                            <span class="mb-0 font-small fw-bold text-gray-900">
                               <strong>{{ request.user.username }}</strong>
                            </span>
                          </div>
                        </div>
                      </a>
                      <div class="dropdown-menu dashboard-dropdown dropdown-menu-end mt-2 py-1">
                        <a class="dropdown-item d-flex align-items-center" href="/settings.html">
                          <svg class="dropdown-icon text-gray-400 me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-6-3a2 2 0 11-4 0 2 2 0 014 0zm-2 4a5 5 0 00-4.546 2.916A5.986 5.986 0 0010 16a5.986 5.986 0 004.546-2.084A5 5 0 0010 11z" clip-rule="evenodd"></path></svg>
                          My Profile
                        </a>
                        <div role="separator" class="dropdown-divider my-1"></div>
                        <a class="dropdown-item d-flex align-items-center" href="{% url 'account:logout' %}">
                          <svg class="dropdown-icon text-danger me-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path></svg>                
                          Logout
                        </a>
                      </div>
                    </li>
                  </ul>
                </div>
              </div>
            </nav>

opi/apps/templates/includes/scripts.html
<!-- Core -->
<script src="/static/assets/vendor/@popperjs/core/dist/umd/popper.min.js"></script>
<script src="/static/assets/vendor/bootstrap/dist/js/bootstrap.min.js"></script>

<!-- Vendor JS -->
<script src="/static/assets/vendor/onscreen/dist/on-screen.umd.min.js"></script>

<!-- Slider -->
<script src="/static/assets/vendor/nouislider/distribute/nouislider.min.js"></script>

<!-- Smooth scroll -->
<script src="/static/assets/vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js"></script>

<!-- Charts -->
<script src="/static/assets/vendor/chartist/dist/chartist.min.js"></script>
<script src="/static/assets/vendor/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js"></script>

<!-- Datepicker -->
<script src="/static/assets/vendor/vanillajs-datepicker/dist/js/datepicker.min.js"></script>

<!-- Sweet Alerts 2 -->
<script src="/static/assets/vendor/sweetalert2/dist/sweetalert2.all.min.js"></script>

<!-- Moment JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>

<!-- Vanilla JS Datepicker -->
<script src="/static/assets/vendor/vanillajs-datepicker/dist/js/datepicker.min.js"></script>

<!-- Notyf -->
<script src="/static/assets/vendor/notyf/notyf.min.js"></script>

<!-- Simplebar -->
<script src="/static/assets/vendor/simplebar/dist/simplebar.min.js"></script>

<!-- Github buttons -->
<script async defer src="https://buttons.github.io/buttons.js"></script>

<!-- Volt JS -->
<script src="/static/assets/js/volt.js"></script>
<script src="/static/htmx.min.js" defer></script>

opi/apps/templates/includes/settings-box.html
    <div class="theme-settings card bg-gray-800 pt-2 collapse" id="theme-settings">
        <div class="card-body bg-gray-800 text-white pt-4">
            <button type="button" class="btn-close theme-settings-close" aria-label="Close" data-bs-toggle="collapse"
                href="#theme-settings" role="button" aria-expanded="false" aria-controls="theme-settings"></button>
            <div class="d-flex justify-content-between align-items-center mb-3">
                <p class="m-0 mb-1 me-4 fs-7">Open source <span role="img" aria-label="gratitude">💛</span></p>
                <a class="github-button" href="https://github.com/themesberg/volt-bootstrap-5-dashboard"
                    data-color-scheme="no-preference: dark; light: light; dark: light;" data-icon="octicon-star"
                    data-size="large" data-show-count="true"
                    aria-label="Star themesberg/volt-bootstrap-5-dashboard on GitHub">Star</a>
            </div>
            <a href="https://themesberg.com/product/admin-dashboard/volt-bootstrap-5-dashboard" target="_blank"
                class="btn btn-secondary d-inline-flex align-items-center justify-content-center mb-3 w-100">
                Download 
                <svg class="icon icon-xs ms-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M2 9.5A3.5 3.5 0 005.5 13H9v2.586l-1.293-1.293a1 1 0 00-1.414 1.414l3 3a1 1 0 001.414 0l3-3a1 1 0 00-1.414-1.414L11 15.586V13h2.5a4.5 4.5 0 10-.616-8.958 4.002 4.002 0 10-7.753 1.977A3.5 3.5 0 002 9.5zm9 3.5H9V8a1 1 0 012 0v5z" clip-rule="evenodd"></path></svg>
            </a>
            <p class="fs-7 text-gray-300 text-center">Available in the following technologies:</p>
            <div class="d-flex justify-content-center">
                <a class="me-3" href="https://themesberg.com/product/admin-dashboard/volt-bootstrap-5-dashboard"
                    target="_blank">
                    <img src="/static/assets/img/technologies/bootstrap-5-logo.svg" class="image image-xs">
                </a>
                <a href="https://demo.themesberg.com/volt-react-dashboard/#/" target="_blank">
                    <img src="/static/assets/img/technologies/react-logo.svg" class="image image-xs">
                </a>
            </div>
        </div>
    </div>

    <div class="card theme-settings bg-gray-800 theme-settings-expand" id="theme-settings-expand">
        <div class="card-body bg-gray-800 text-white rounded-top p-3 py-2">
            <span class="fw-bold d-inline-flex align-items-center h6">
                <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M11.49 3.17c-.38-1.56-2.6-1.56-2.98 0a1.532 1.532 0 01-2.286.948c-1.372-.836-2.942.734-2.106 2.106.54.886.061 2.042-.947 2.287-1.561.379-1.561 2.6 0 2.978a1.532 1.532 0 01.947 2.287c-.836 1.372.734 2.942 2.106 2.106a1.532 1.532 0 012.287.947c.379 1.561 2.6 1.561 2.978 0a1.533 1.533 0 012.287-.947c1.372.836 2.942-.734 2.106-2.106a1.533 1.533 0 01.947-2.287c1.561-.379 1.561-2.6 0-2.978a1.532 1.532 0 01-.947-2.287c.836-1.372-.734-2.942-2.106-2.106a1.532 1.532 0 01-2.287-.947zM10 13a3 3 0 100-6 3 3 0 000 6z" clip-rule="evenodd"></path></svg>
                Settings
            </span>
        </div>
    </div>