opi/core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from website import urls as wesiturl
from website import views as view
from payment import urls as nhj
from promotion import urls as promotio
from django.views.generic import TemplateView

urlpatterns = [

    url(r'^schedule/', include('schedule.urls')),
    url(r'^fullcalendar/', TemplateView.as_view(template_name="fullcalendar.html"), name='fullcalendar'),

    path('admin/', admin.site.urls),          # Django admin route
    path("", include(("apps.authentication.urls", "account"),namespace='account')), # Auth routes - login / register
    path("", include(("home.urls", "main"),namespace='main')),
    path("", include("allauth.urls")),
    path('webuse/',include("webuser.urls")), #my app urls
    path('website/', include((wesiturl,'website'),namespace='website')),
    path('paypal/', include('paypal.standard.ipn.urls')),      
    path('payment/', include((nhj,'payment'),namespace='payment')),
    url(r'^getdatareport/', view.getdatareport),#api for get usernewuser
    path('newuser/<str:id>', view.newuser),
    path('storedata/<str:id>', view.storedata),#api for requesing from 
   
         # UI Kits Html files

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

opi/website/urls.py
from django.urls import path
from . import views
urlpatterns = [
   path('',views.home),
   path('view',views.vie, name = 'register'),
   path('offerlist/<str:mid>', views.offerlist, name = 'offerlist'),
   path('offerlist_in/<str:mid>/<str:temp>', views.offerlist_in, name = 'offerlist_in'),
   path('webeditpage/<str:mid>', views.webeditpage, name = 'webeditpage'),
   path('cheack', views.cheack, name = 'cheack'),
   path('update/<str:id>', views.update, name = 'update'),
   path('upload/<str:id>', views.upload, name = 'upload'),
   path('upload_first/<str:id>', views.upload_first, name = 'upload_first'),
   path('imupdate/<str:id>', views.imupdate, name = 'imupdate'),
   path('updatetable/<str:id>', views.updatetable, name = 'updatetable'),
   path('removtable/<str:id>', views.removtable, name = 'removtable'),
   path('resat/<str:id>', views.resat, name = 'resat'),
   path('restart/<str:id>', views.restart1, name = 'restart'),
   path('stop/<str:id>', views.stop, name = 'stop'),
   path('reload/<str:id>', views.reload1, name = 'reload'),
   path('registernew', views.registernew, name = 'registernew'),
   path('selectweb_type/<str:name>', views.selectweb_type, name = 'selectweb_type'),
   path('selecttemplate/<str:name>/<str:type1>', views.selecttemplate, name = 'selecttemplate'),
   path('view_template/<str:name>/<str:tmid>', views.view_template, name = 'view_template'),
   path('template_edit/<str:id>', views.template_edit, name = 'template_edit'),

   path('billing/<str:id>', views.billing, name = 'billing'),
   path('select_domain/<str:id>', views.select_domain, name = 'select_domain'),
   path('select_domain_remove/<str:id>', views.select_domain_remove, name = 'select_domain_remove'),
   path('payment/<str:id>', views.payment, name = 'payment'),
   path('dataentrypage/<str:id>', views.dataentrypage, name = 'dataentrypage'),
   path('register_email/<str:id>', views.register_email, name = 'register_email'),
   path('remove_email/<str:id>', views.remove_email, name = 'remove_email'),
   path('setup_promo/<str:id>', views.setup_promo, name = 'setup_promo'),
   path('remove_promo/<str:id>', views.remove_promo, name = 'remove_promo'),
   path('dataentrypage_main/<str:id>', views.dataentrypage_main, name = 'dataentrypage_main'),
   

   path('edit_page/<str:id>', views.edit_pages, name = 'edit_pages'),
   path('upload_first1/<str:id>', views.upload_first1, name = 'upload_first1'),
   path('domain_name/<str:id>', views.domain_name, name = 'domain_name'),
   path('domain_removemain/<str:id>', views.domain_removemain, name = 'domain_removemain'),
   path('domain_selected/<str:id>', views.domain_selec, name = 'domain_selected'),
   path('promotion/<str:id>', views.promotion, name = 'promotion'),
   path('livereport/<str:id>', views.livereport, name = 'livereport'),
   path('messages/<str:id>', views.messages, name = 'messages'),
]

opi/apps/templates/accounts/login.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Sign IN {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}
{% load socialaccount %}
{% block content %}

    <main>
        <section class="vh-lg-100 mt-5 mt-lg-0 bg-soft d-flex align-items-center">
            <div class="container">
                <p class="text-center">
                    Open-source Django Dashboard
                </p>
                <div class="row justify-content-center form-bg-image" data-background-lg="/static/assets/img/illustrations/signin.svg">
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="bg-white shadow border-0 rounded border-light p-4 p-lg-5 w-100 fmxw-500">
                            <div class="text-center text-md-center mb-4 mt-md-0">
                                <h1 class="mb-0 h3">
                                    Django Volt - Sign IN
                                </h1>
                                <br />
                                <p>
                                    {% if msg %}
                                        {{ msg | safe }}
                                    {% else %}
                                        Add your credentials
                                    {% endif %}                                     
                                </p> 
                            </div>
                            <form method="post" action="" class="mt-4">
                                
                                {% csrf_token %}

                                <!-- Form -->
                                <div class="form-group mb-4">
                                    <label for="email">Username</label>
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon1">
                                            <span class="fas fa-user-circle"></span>
                                        </span>
                                        {{ form.username }}
                                    </div>  
                                </div>
                                <!-- End of Form -->
                                <div class="form-group">
                                    <!-- Form -->
                                    <div class="form-group mb-4">
                                        <label for="password">Your Password</label>
                                        <div class="input-group">
                                            <span class="input-group-text" id="basic-addon2">
                                                <span class="fas fa-unlock-alt"></span>
                                            </span>
                                            {{ form.password }}
                                        </div>  
                                    </div>
                                    <!-- End of Form -->
                                    <div class="d-flex justify-content-between align-items-top mb-4">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" id="remember">
                                            <label class="form-check-label mb-0" for="remember">
                                              Remember me
                                            </label>
                                        </div>
                                        <div><a href="/page-forgot-password.html" class="small text-right">Lost password?</a></div>
                                    </div>
                                </div>
                                <div class="d-grid">
                                    <button type="submit" name="login" class="btn btn-gray-800">Sign IN</button>
                                </div>
                            </form>
                            <br />
                            
                            <div class="mt-3 mb-4 text-center">
                                <span class="fw-normal">or login with</span>
                            </div>
                            <div class="d-flex justify-content-center my-4">
                                <a href="{% provider_login_url 'google'%}?next=/" class="btn btn-icon-only btn-pill btn-outline-gray-500 me-2" aria-label="facebook button" title="facebook button">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-google" viewBox="0 0 16 16">
                                        <path d="M15.545 6.558a9.42 9.42 0 0 1 .139 1.626c0 2.434-.87 4.492-2.384 5.885h.002C11.978 15.292 10.158 16 8 16A8 8 0 1 1 8 0a7.689 7.689 0 0 1 5.352 2.082l-2.284 2.284A4.347 4.347 0 0 0 8 3.166c-2.087 0-3.86 1.408-4.492 3.304a4.792 4.792 0 0 0 0 3.063h.003c.635 1.893 2.405 3.301 4.492 3.301 1.078 0 2.004-.276 2.722-.764h-.003a3.702 3.702 0 0 0 1.599-2.431H8v-3.08h7.545z"/>
                                      </svg>
                                </a>
                                
                            </div>

                            <div class="d-flex justify-content-center align-items-center mt-4">
                                <span class="fw-normal">
                                    Not registered?
                                    <a href="{% url 'account:register' %}" class="fw-bold">Create account</a>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

opi/apps/templates/accounts/register.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Sign UP {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <main>
        <section class="vh-lg-100 mt-5 mt-lg-0 bg-soft d-flex align-items-center">
            <div class="container">
                <p class="text-center">
                    Open-source Django Dashboard
                </p>
                <div class="row justify-content-center form-bg-image" data-background-lg="/static/assets/img/illustrations/signin.svg">
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="bg-white shadow border-0 rounded border-light p-4 p-lg-5 w-100 fmxw-500">
                            <div class="text-center text-md-center mb-4 mt-md-0">
                                <h1 class="mb-0 h3">
                                    Django Volt - Sign UP
                                </h1>
                                <br />
                                <p>
                                    {% if msg %}
                                        {{ msg | safe }}
                                    {% else %}
                                        Add your credentials
                                    {% endif %}                                     
                                </p> 
                            </div>
                            <form method="post" action="" class="mt-4">
                                
                                {% csrf_token %}

                                <div class="form-group mb-4">
                                    <label for="email">Username</label>
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon1">
                                            <span class="fas fa-user-circle"></span>
                                        </span>
                                        {{ form.username }}
                                    </div>  
                                    <span class="text-error">{{ form.username.errors }}</span>
                                </div>

                                <!-- Form -->
                                <div class="form-group mb-4">
                                    <label for="email">Your Email</label>
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon1">
                                            <span class="fas fa-envelope"></span>
                                        </span>
                                        {{ form.email }}
                                    </div>  
                                    <span class="text-error">{{ form.email.errors }}</span>
                                </div>
                                <!-- End of Form -->
                                <div class="form-group">
                                    
                                    <!-- Form -->
                                    <div class="form-group mb-4">
                                        <label for="password">Your Password</label>
                                        <div class="input-group">
                                            <span class="input-group-text" id="basic-addon2">
                                                <span class="fas fa-unlock-alt"></span>
                                            </span>
                                            {{ form.password1 }}
                                        </div>  
                                        <span class="text-error">{{ form.password1.errors }}</span>
                                    </div>
                                    <div class="form-group mb-4">
                                        <label for="password">Password Confirmation</label>
                                        <div class="input-group">
                                            <span class="input-group-text" id="basic-addon2">
                                                <span class="fas fa-unlock-alt"></span>
                                            </span>
                                            {{ form.password2 }}
                                        </div>  
                                        <span class="text-error">{{ form.password2.errors }}</span>
                                    </div>

                                    <!-- End of Form -->
                                    <div class="mb-4">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" id="remember">
                                            <label class="form-check-label fw-normal mb-0" for="remember">
                                                I agree to the <a href="#" class="fw-bold">terms and conditions</a>
                                            </label>
                                        </div>
                                    </div>
                                </div>
                                <div class="d-grid">
                                    <button type="submit" name="register" class="btn btn-gray-800">Sign UP</button>
                                </div>
                            </form>
                            <br />
                            <!--
                            <div class="mt-3 mb-4 text-center">
                                <span class="fw-normal">or login with</span>
                            </div>
                            <div class="d-flex justify-content-center my-4">
                                <a href="#" class="btn btn-icon-only btn-pill btn-outline-gray-500 me-2" aria-label="facebook button" title="facebook button">
                                    <svg class="icon icon-xxs" aria-hidden="true" focusable="false" data-prefix="fab" data-icon="facebook-f" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512"><path fill="currentColor" d="M279.14 288l14.22-92.66h-88.91v-60.13c0-25.35 12.42-50.06 52.24-50.06h40.42V6.26S260.43 0 225.36 0c-73.22 0-121.08 44.38-121.08 124.72v70.62H22.89V288h81.39v224h100.17V288z"></path></svg>
                                </a>
                                <a href="#" class="btn btn-icon-only btn-pill btn-outline-gray-500 me-2" aria-label="twitter button" title="twitter button">
                                    <svg class="icon icon-xxs" aria-hidden="true" focusable="false" data-prefix="fab" data-icon="twitter" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z"></path></svg>
                                </a>
                                <a href="#" class="btn btn-icon-only btn-pill btn-outline-gray-500" aria-label="github button" title="github button">
                                    <svg class="icon icon-xxs" aria-hidden="true" focusable="false" data-prefix="fab" data-icon="github" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512"><path fill="currentColor" d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"></path></svg>
                                </a>
                            </div>-->

                            <div class="d-flex justify-content-center align-items-center mt-4">
                                <span class="fw-normal">
                                    Already have an account? 
                                    <a href="{% url 'account:login' %}" class="fw-bold">Sign IN</a>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}